model:
  checkpoint: ./pretrained_models/pretrained_diffusion.pt

guide_models:
  - name: binding_affinity
    checkpoint: ./logs/training_dock_guide_2023_12_17__06_23_35/checkpoints/184000.pt
    weight: 1
    guide_kind: Kd
    gradient_scale_cord: 2.0
    gradient_scale_categ: 0.0 #1e-10

sample:
  seed: 2021
  num_samples: 100
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior

