model:
  checkpoint: ./pretrained_models/pretrained_diffusion.pt

guide_models:
  - name: qed
    checkpoint: ./logs/training_dock_guide_qed_2024_01_06__01_35_21/checkpoints/186000.pt
    weight: 0.33
    guide_kind: Kd
    gradient_scale_cord: 20
    gradient_scale_categ: 0.0 #1e-10
    clamp_pred_max: 1.0
  - name: sa
    checkpoint: ./logs/training_dock_guide_sa_2024_01_20__15_38_49/checkpoints/162000.pt
    weight: 0.33
    guide_kind: Kd
    gradient_scale_cord: 5
    gradient_scale_categ: 0.0 #1e-10
    clamp_pred_max: 1.0
  - name: binding_affinity
    checkpoint: ./logs/training_dock_guide_2023_12_17__06_23_35/checkpoints/184000.pt
    weight: 0.34
    guide_kind: Kd
    gradient_scale_cord: 2.0
    gradient_scale_categ: 0.0 #1e-10

sample:
  seed: 2021
  num_samples: 100
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior

